# Generated by Django 3.2.8 on 2021-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211128_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
