# Generated by Django 3.2.8 on 2021-11-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211128_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='words',
            new_name='tag',
        ),
    ]
