# Generated by Django 3.2.8 on 2021-11-28 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_words_tag_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
