# Generated by Django 3.2.8 on 2021-11-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/homepage/')),
            ],
        ),
        migrations.CreateModel(
            name='webData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('About_me', models.TextField()),
                ('mine_name', models.CharField(max_length=50)),
                ('HomePage_qoute', models.TextField()),
                ('Homepage_slide_imgs', models.ManyToManyField(to='blog.sliderImages')),
            ],
        ),
    ]
