# Generated by Django 3.2.8 on 2021-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_sliderimages_webdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webdata',
            name='Homepage_slide_imgs',
            field=models.ManyToManyField(null=True, to='blog.sliderImages'),
        ),
    ]
