# Generated by Django 3.2.8 on 2021-11-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20211128_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
