# Generated by Django 3.2.8 on 2021-11-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_sliderimages_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='Homepage_slide_imgs',
        ),
        migrations.AddField(
            model_name='webdata',
            name='slide_img',
            field=models.ManyToManyField(to='blog.sliderImages'),
        ),
        migrations.AlterField(
            model_name='sliderimages',
            name='img',
            field=models.ImageField(default=1, upload_to='images/homepage/'),
            preserve_default=False,
        ),
    ]
