# Generated by Django 3.2.8 on 2021-11-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20211128_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimages',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
