# Generated by Django 3.2.8 on 2021-11-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_sliderimages_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='slide_img',
        ),
        migrations.AddField(
            model_name='webdata',
            name='slider1',
            field=models.ImageField(null=True, upload_to='images/homepage/'),
        ),
        migrations.AddField(
            model_name='webdata',
            name='slider2',
            field=models.ImageField(null=True, upload_to='images/homepage/'),
        ),
        migrations.AddField(
            model_name='webdata',
            name='slider3',
            field=models.ImageField(null=True, upload_to='images/homepage/'),
        ),
        migrations.DeleteModel(
            name='sliderImages',
        ),
    ]
