# Generated by Django 3.2.8 on 2021-11-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20211128_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='webdata',
            name='slider3',
        ),
    ]
