# Generated by Django 3.2.8 on 2021-11-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
