# Generated by Django 4.0.2 on 2022-07-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_contactme_contacted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='message',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='title',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='HTML_Templete',
            field=models.FileField(default=12, upload_to='Newsletter/'),
            preserve_default=False,
        ),
    ]
