# Generated by Django 4.0.2 on 2022-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_rename_message_mailmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='HTML_Templete',
            field=models.FileField(max_length=254, upload_to='Newsletter/% Y/% m/% d/'),
        ),
    ]
