# Generated by Django 4.0.2 on 2022-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_mailmessage_html_templete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailmessage',
            old_name='subject',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='mailmessage',
            name='HTML_Templete',
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
