# Generated by Django 4.0.2 on 2022-09-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_blog_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webdata',
            name='socail_link',
            field=models.URLField(null=True),
        ),
    ]
