# Generated by Django 4.0.2 on 2022-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_rename_socail_link_webdata_socail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='DataBase/Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(upload_to='DataBase/Images/Projects/logo'),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='my_image',
            field=models.ImageField(upload_to='DataBase/Images/Homepage'),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='slider1',
            field=models.ImageField(null=True, upload_to='DataBase/Images/Homepage/'),
        ),
    ]
