# Generated by Django 4.0.2 on 2022-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_blog_image_alter_blog_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webdata',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
