# Generated by Django 4.0.2 on 2022-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_webdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='Images/BlogImages'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='logo',
            field=models.ImageField(upload_to='Images/Projects/logo'),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='my_image',
            field=models.ImageField(upload_to='Images/WebData'),
        ),
        migrations.AlterField(
            model_name='webdata',
            name='slider1',
            field=models.ImageField(null=True, upload_to='Images/WebData'),
        ),
    ]
