# Generated by Django 4.2.8 on 2023-12-19 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0064_blog_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateField(auto_now=True)),
                ("toolName", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        null=True,
                        upload_to="Images/Tools",
                        validators=[
                            django.core.validators.FileExtensionValidator(["svg"])
                        ],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="projects",
            name="logo",
        ),
        migrations.AddField(
            model_name="projects",
            name="Thumbnail",
            field=models.ImageField(default=0, upload_to="Images/Projects/Thumbnail"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects",
            name="tools",
            field=models.ManyToManyField(to="blog.projecttools"),
        ),
    ]
