# Generated by Django 4.2.8 on 2023-12-19 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0065_projecttools_remove_projects_logo_projects_thumbnail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projects",
            name="projectType",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projects",
            name="skills",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="projecttools",
            name="logo",
            field=models.FileField(
                default=1,
                upload_to="Images/Tools",
                validators=[django.core.validators.FileExtensionValidator(["svg"])],
            ),
            preserve_default=False,
        ),
    ]
