# Generated by Django 4.2.8 on 2023-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0066_blog_publish_projects_projecttype_projects_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttools",
            name="publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projecttools",
            name="type",
            field=models.CharField(
                choices=[
                    ("tool", "TOOL"),
                    ("framework", "FRAMEWORK"),
                    ("library", "LIBRARY"),
                    ("language ", "LANGUAGE"),
                ],
                default="tool",
                max_length=20,
            ),
        ),
    ]
