# Generated by Django 6.0.7 on 2026-07-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_projecttools_publish_projecttools_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=18.5204, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=73.8567, max_digits=9)),
                ('location_name', models.CharField(default='Pune, India', max_length=150)),
                ('mood', models.CharField(default='Coding', max_length=100)),
                ('mood_emoji', models.CharField(default='💻', max_length=10)),
                ('music_title', models.CharField(default='Starboy', max_length=150)),
                ('music_artist', models.CharField(default='The Weeknd', max_length=150)),
                ('music_is_playing', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
