# Generated by Django 6.0.7 on 2026-07-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0068_profilestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Instagram/Images/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('likes', models.IntegerField(default=142)),
                ('comments', models.IntegerField(default=12)),
                ('post_url', models.URLField(default='https://instagram.com/sudarshan_kakde_', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
