# Generated by Django 6.0.7 on 2026-07-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_instagrampost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstagramPost',
        ),
        migrations.AddField(
            model_name='webdata',
            name='resume_url',
            field=models.URLField(blank=True, help_text='Google Drive preview link for resume', max_length=500, null=True),
        ),
    ]
