# Generated by Django 6.0.7 on 2026-07-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_delete_instagrampost_webdata_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pin this blog to the top of the list'),
        ),
    ]
