# Generated by Django 6.0.7 on 2026-07-18 10:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_blog_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='case_study',
            field=models.TextField(blank=True, help_text='Detailed project case study content (HTML/TinyMCE)', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository URL', null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(help_text='Live demo URL'),
        ),
    ]
