# Generated by Django 6.0.7 on 2026-07-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_projects_case_study_projects_github_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileStatus',
        ),
    ]
