# Generated by Django 6.0.7 on 2026-07-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_delete_profilestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('period', models.CharField(help_text='e.g. June 2023 - Aug 2023', max_length=100)),
                ('responsibilities', models.TextField(help_text='Enter each responsibility on a new line')),
                ('type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job'), ('offer_letter', 'Offer Letter')], default='job', max_length=20)),
                ('certificate', models.FileField(blank=True, help_text='Upload certificate file', null=True, upload_to='Certificates/')),
                ('certificate_url', models.URLField(blank=True, help_text='Or enter certificate URL', max_length=500, null=True)),
                ('publish', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Ordering index (smaller first or larger first, default is descending by id)')),
            ],
        ),
    ]
