# Generated by Django 6.0.7 on 2026-07-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ranking',
            field=models.IntegerField(default=10, help_text='Ranking order (smaller values first)'),
        ),
    ]
