# Generated by Django 6.0.7 on 2026-07-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_projects_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Gallery Image', help_text='Label text displayed under image card', max_length=100)),
                ('image', models.ImageField(upload_to='Images/Gallery')),
                ('order', models.IntegerField(default=0, help_text='Ordering index (smaller values first)')),
                ('publish', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
